import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import ResponsiveNavbar from "@/components/shareUi/navbar";
import Footer from "@/components/shareUi/footer";
import WebVitals from "@/components/web-vitals";
import Providers from "@/Provider/Providers";
import AutoLocationTracker from "@/tracker/tracker";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "DeliverSync Platform",
  description: "Generated by DeliverSync Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Providers>
            <AutoLocationTracker />
          <div className="pt-16 md:pt-20 mb-8">
            <ResponsiveNavbar />
          </div>
          <WebVitals />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
